#!python3
# -*- coding: utf-8 -*-
"""
First major step is to roughly process the data and to detect long stop periods in order to cut portions of data between long stops
Created on 20/09/24
"""
from typing import List
import pandas as pd

from artemis_gnss.config import Config
from artemis_gnss.process.iterative.abc import StatefulStep
from artemis_gnss.process.options import CleanOptions
from artemis_gnss.process.iterative.E_merge_portions import portion_decide_merge
from artemis_gnss.process.b_clean_raw_stop_detection import clean_raw_steps, stop_or_gap_divide


class SplitTraceStep(StatefulStep):
    """
    This process splits a raw trace into a collection of portions.
    It is the stateful implementation which keeps in memory the residual_trace for the following treatment.
    """

    def __init__(self):
        super().__init__()
        self.residual_trace_since_long_stop: pd.DataFrame = None  # unfinished portion
        self.debug_history_portions_raw: List[pd.DataFrame] = None  # debug field containing the list of the portions generated by the process + residual / None

    def initialize(self, *args, **kwargs):
        self.residual_trace_since_long_stop = None
        self.debug_history_portions_raw = []

    def append(self, trace: pd.DataFrame, options: CleanOptions, *args, **kwargs) -> List[pd.DataFrame]:
        clean_raw_steps(trace, options)
        prepend_unmerged_residual = False
        if self.residual_trace_since_long_stop is not None:
            # append trace to residual_trace if exists and eligible to merge, keeping attributes of trace
            if portion_decide_merge(self.residual_trace_since_long_stop, trace):
                trace_attrs_copy = trace.attrs
                trace = pd.concat((self.residual_trace_since_long_stop, trace))
                trace.attrs = trace_attrs_copy
                self.residual_trace_since_long_stop = None
            else:
                prepend_unmerged_residual = True
        portions, residual_trace = stop_or_gap_divide(trace, duration_cut_s=Config.STOP_DURATION_MAX__CUT_sec)
        if prepend_unmerged_residual:
            list.insert(portions, 0, self.residual_trace_since_long_stop)
            self.residual_trace_since_long_stop = None
        self.residual_trace_since_long_stop = residual_trace
        if Config.ENABLE_DEBUG:
            self.debug_history_portions_raw += portions
        return portions

    def purge_last_step(self, *args, **kwargs) -> List[pd.DataFrame]:
        """
        Last call to this step releases the residual trace and returns it.

        :param args:
        :param kwargs:
        :return: List containing the residual trace or None
        """
        # NB: returns None or List with one element
        residual_portion = self.residual_trace_since_long_stop
        self.residual_trace_since_long_stop = None
        if Config.ENABLE_DEBUG:
            self.debug_history_portions_raw.append(residual_portion)
        return [residual_portion] if residual_portion is not None else None

    def flush_purge_and_reset(self, *args, **kwargs) -> List[pd.DataFrame]:
        """
        Last call and reset.

        :see: purge_last_step
        :param args:
        :param kwargs:
        :return:
        """
        output = self.purge_last_step()
        self.initialize()
        return output

    def get_state(self) -> dict:
        return {"cut_residual_trace": self.residual_trace_since_long_stop.to_dict()}

    def restore(self, state: dict):
        self.residual_trace_since_long_stop = pd.DataFrame.from_dict(state["cut_residual_trace"])
