#!python3
# -*- coding: utf-8 -*-
"""
This step merges portions
Created on 20/09/24
"""
from typing import List
import datetime

import numpy as np
import pandas as pd

from artemis_gnss.config import Config
from artemis_gnss.process.iterative.abc import StatefulStep
from artemis_gnss.process.options import CleanOptions
from artemis_gnss.process.d_clean_portion import clean_portion_steps
from artemis_gnss.process.f_clean_trip_post_merge import clean_trip_post_merge_steps
from artemis_gnss.algos.exceptions import TimeOverlayException
from artemis_gnss.algos.condition_intervals import propagate_diff_cond
from artemis_gnss.algos.gps_position import pos_diff_distance_2_points
from artemis_gnss.enum_attrs import GenerationType

merge_edit_init_last_trip = True


def portion_decide_merge(current_trip: pd.DataFrame, portion: pd.DataFrame) -> bool:
    """
    This function checks if a portion can be merged to a trip under construction.
    If it not the case, the trip must be finalized and the portion must become the beginning of the next trip.
    :param current_trip: trip under construction
    :param portion: portion to add
    :return: True if ok to merge
    """
    if "speed" in current_trip:
        bool_space_gap = propagate_diff_cond(current_trip["int_gps_distance_step"].values[1:] > Config.SPACE_GAP_THRESHOLD_m_s)
        bool_move = np.logical_or(current_trip["speed"].values > Config.SPEED_STOP_THRESHOLD_low_m_s, bool_space_gap)
        i_trip_last_move = np.argwhere(bool_move)
        trip_has_movement = len(i_trip_last_move) > 0
        i_trip_last_move = i_trip_last_move[-1][-1] if trip_has_movement            else 0
        bool_space_gap = propagate_diff_cond(portion["int_gps_distance_step"].values[1:] > Config.SPACE_GAP_THRESHOLD_m_s)
        bool_move = np.logical_or(portion["speed"].values > Config.SPEED_STOP_THRESHOLD_low_m_s, bool_space_gap)
        i_portion_first_move = np.argwhere(bool_move)
        portion_has_movement = len(i_portion_first_move) > 0
        i_portion_first_move = i_portion_first_move[0][0] if portion_has_movement else 0
    else:
        i_trip_last_move = len(current_trip) - 1
        i_portion_first_move = 0
    t0, t1 = current_trip["time"].values[i_trip_last_move], portion["time"].values[i_portion_first_move]
    duration = t1 - t0
    if duration < 0:
        raise TimeOverlayException(t0, t1)
    decide_merge = duration < Config.DISPLACEMENT_MAX_TIME_GAP_sec
    if (not trip_has_movement) and (not portion_has_movement):
        decide_merge = True
    if Config.ENABLE_DEBUG:
        portion.attrs["debug"]["decide_merge"] = decide_merge
    return decide_merge


class MergePortionStep(StatefulStep):
    def __init__(self):
        self.current_trip: pd.DataFrame = None  # trip under construction
        self.previous_trip: pd.DataFrame = None  # last trip returned
        self.previous_portion: pd.DataFrame = None  # last portion
        # mechanism to merge with last trip in database
        self.init_last_trip: pd.DataFrame = None  # last trip given as input
        self.init_last_trip_has_changed: bool = False  # bool to tell if init_last_trip was modified
        self.init_last_trip_edit: pd.DataFrame = None  # last trip given as input after merge
        self._init_last_trip_passed: bool = True  # boolean becomes True if a new trip has been added past the init_last_trip
        # debug lists
        self.debug_history_portions_clean: List[pd.DataFrame] = None  # debug field containing the list of the portions after clean
        self.debug_history_trips: List[pd.DataFrame] = None  # debug field containing the list of the trips generated by the process + residual / None - should be +/- equal to main.trips

    def initialize(self, init_last_trip: pd.DataFrame = None, *args, **kwargs):
        if merge_edit_init_last_trip:
            self.current_trip, self.previous_trip = init_last_trip, None
            self._init_last_trip_passed = init_last_trip is None
        else:
            self.current_trip, self.previous_trip = None, init_last_trip
            self._init_last_trip_passed = True
        self.previous_portion = init_last_trip
        self.init_last_trip = init_last_trip
        self.init_last_trip_has_changed = False
        self.init_last_trip_edit = init_last_trip
        self.debug_history_portions_clean = []
        self.debug_history_trips = []

    def append(self, trace: pd.DataFrame, options: CleanOptions, *args, **kwargs) -> List[pd.DataFrame]:
        new_trips = []
        clean = clean_portion_steps(trace, previous_portion=self.previous_portion, options=options)
        if clean is not None:
            self.previous_portion = clean
            self.debug_history_portions_clean.append(clean)
        else:
            return []
        if self.current_trip is None:
            self.current_trip = clean
        elif portion_decide_merge(self.current_trip, clean):
            self.current_trip = pd.concat((self.current_trip, clean))
        else:
            new_trips_add, self.previous_trip = clean_trip_post_merge_steps(self.current_trip, options, previous_trip=self.previous_trip,
                                                                            is_last_trip=False)
            new_trips += new_trips_add
            if merge_edit_init_last_trip and not self._init_last_trip_passed:
                if len(new_trips) == 0:
                    if self.previous_trip is not None:
                        self._init_last_trip_passed = False  # maintain flag until new_trips contains something
                    else:
                        self.init_last_trip_edit = None  # destroy init_last_trip
                        self.init_last_trip_has_changed = True
                        self._init_last_trip_passed = True
                elif not new_trips[0] == self.init_last_trip:
                    self.init_last_trip_edit = new_trips.pop(0)  # replace init_last_trip & remove from outputs
                    self.init_last_trip_has_changed = True
                    self._init_last_trip_passed = True
            self.current_trip = clean
        if Config.ENABLE_DEBUG:
            self.debug_history_trips += new_trips
        return new_trips

    def purge(self, options: CleanOptions, *args, **kwargs) -> List[pd.DataFrame]:
        # NB: returns None or List with one element
        if self.current_trip is not None:
            last_trip = self.current_trip
            residuals, _ = clean_trip_post_merge_steps(last_trip, options, previous_trip=self.previous_trip,
                                                       is_last_trip=True)
            if residuals:
                self.previous_trip = residuals[-1]
            self.current_trip = None
        else:
            residuals = []
        if Config.ENABLE_DEBUG:
            self.debug_history_trips += residuals
        return residuals

    def flush(self, options: CleanOptions, *args, **kwargs) -> List[pd.DataFrame]:
        output = self.purge(options)
        self.initialize()
        return output

    def get_state(self) -> dict:
        return {"merge_current_trip": self.current_trip.to_dict(),
                "merge_previous_trip": self.previous_trip.to_dict(),
                "merge_previous_portion": self.previous_portion.to_dict()}

    def restore(self, state: dict, history_trips: List[pd.DataFrame]=None):
        self.current_trip = pd.DataFrame.from_dict(state["merge_current_trip"])
        self.previous_trip = pd.DataFrame.from_dict(state["merge_previous_trip"])
        self.previous_portion = pd.DataFrame.from_dict(state["merge_previous_portion"])
        if history_trips is None:
            history_trips = []
        self.init_last_trip = None  # last trip given as input
        self.init_last_trip_has_changed = False  # bool to tell if init_last_trip was modified
        self.init_last_trip_edit = None  # last trip given as input after merge
        self._init_last_trip_passed = True  # boolean becomes True if a new trip has been added past the init_last_trip
        self.debug_history_trips = history_trips
        self.debug_history_portions_clean = []

